version: '3'
services:
  autodelete:
    image: ghcr.io/siebsie23/s3-deleter:latest
    environment:
      SERVER_URL: https://eu2.contabostorage.com
      ACCESS_KEY: 1234567890
      SECRET_KEY: 1234567890
      REGION: eu-central-1
      DELETE_AFTER_DAYS: 10
      BUCKETS: bucket1,bucket2,bucket3
